name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # Runs every hour
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # Required
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: sirishshrestha84
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu

          # Plugins (choose what you want)
          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_repositories: 100
          plugin_achievements: yes
          plugin_activity: yes
